myapp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name="index"),
    path("post/<int:post_id>", views.detail, name="detail"),
    path("new_url",views.new_url_view, name="new_url_name"),
    path("old_url",views.old_url_redirect, name="old_url"),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'myapp.views.custom_page_not_found'
urlpatterns = [
    path("blog/",include("blog.urls")),
    path('admin/', admin.site.urls),
]

myapp/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)  # Fixed typo
    content = models.TextField()
    img_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title

myapp/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import reverse
# Create your views here.
posts = [
        {'id':1,'title':'Post 1','content':'content of post 1'},
        {'id':2,'title':'Post 2','content':'content of post 2'},
        {'id':3,'title':'Post 3','content':'content of post 3'},
        {'id':4,'title':'Post 4','content':'content of post 4'},
]

def index(request):
    
    return render(request,"index.html",{"posts":posts})

def detail(request,post_id):
    post = next((item for item in posts if item['id']==int(post_id)),None)
    return render(request,"detail.html",{'post':post})

def old_url_redirect(request):
    return redirect(reverse('blog:new_url_name'))

def new_url_view(request):
    return HttpResponse("This is the new Url")

myapp/myapp/views.py
from django.shortcuts import render

def custom_page_not_found(request,exception):
    return render(request,'404.html', status=404) 

myapp/blog/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >
    <header class="p-3 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h3>Blog</h3>
            </div>
            <div class="col">
                <div class="d-flex justify-content-center gap-3">
                    <a class="text-light text-decoration-none" href="">Home</a>
                    <a class="text-light text-decoration-none" href="">About</a>
                    <a class="text-light text-decoration-none" href="">Contact</a>
                </div>
            </div>
        </div>
    </header>
  
      {% block content %}
      {% endblock %}

    <footer class="bg-dark text-light p-3">
        <div class="col-4 d-flex justify-content-center align-items-center">
          <span class="text-light">© 2025 Company, Inc</span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

myapp/blog/templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}}</h1>
              <p class="text-muted">Posted on January 1, 2024</p>
              <img src="https://via.placeholder.com/800x400" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    <li><a href="./detail.html">Post 1</a></li>
                    <li><a href="./detail.html">Post 2</a></li>
                    <li><a href="./detail.html">Post 3</a></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
    <footer class="bg-dark text-light p-3 fixed-bottom">
        <div class="col-4 d-flex justify-content-center align-items-center">
          <span class="text-light">© 2021 Company, Inc</span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% endblock %}

myapp/blog/templates/index.html
    {% extends 'base.html' %}
    {% block content %}
    <div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <h2 >Latest Posts</h2>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                    <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                      <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                    </button>
                  </div>
            </div>
        </div>
        <div class="row m-3">
            {%if posts%}

            {%for post in posts%}
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="{% url 'blog:detail' post_id=post.id%}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">Sports</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
            {%else%}
            <div>No Posts Available</div>
            {%endif%}
            
        </div>
        <div class="row">
           
        </div>
        
    </div>
    {% endblock %}